[package]
name = "content-security-policy"
version = "0.0.0"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "Will parse and validate Content-Security-Policy level 3"
keywords = ["http", "csp", "security"]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/content-security-policy/"
repository = "https://github.com/notriddle/rust-content-security-policy"
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
bitflags = "1.0.0"
lalrpop-util = "0.13.1"
regex = "0.2.2"
url = "1.5.1"

[dev-dependencies]
version-sync = "0.3"
