[package]
name = "content-security-policy"
version = "0.0.0"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "Will parse and validate Content-Security-Policy level 3"
keywords = ["http", "csp", "security"]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/content-security-policy/"
repository = "https://github.com/notriddle/rust-content-security-policy"

[dependencies]
